aarch64_va_bits:
  type: int
  default: 48
  constraint: "{{value}} == 48 or {{value}} == 44 or {{value}} == 39"
  help:
    Number of bits to use for virtual address (VA). The same value is used for
    user and kernel mode.

aarch64_page_size:
  type: int
  default: 4096
  constraint: "{{value}} == 4096"
  help:
    Number of bytes per page.

aarch64_pan:
  type: bool
  default: false
  help:
    Enable Privileged Access Never (PAN).

arch_supports_fast_thread_access:
  type: bool
  default: true
